sudo: required
services:
    - docker

before_install:
    - docker build -t hdimessi/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true hdimessi/docker-react npm run test
deploy:
    provider: elasticbeanstalk
    region: "eu-west-3"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-3-542896382797"
    bucket_path: "docker-react"
    on:
        branck: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"

